export type RootStackParamList = {
  About: undefined;
  AcceptInvite: undefined;
  BoostProperty: { propertyId: string };
  Favorites: undefined;
  ChangePassword: undefined;
  Contact: undefined;
  EditProfile: undefined;
  Login: undefined;
  NotificationDetail: { notification: { body: string; created_at: string; id: string; is_read: boolean; metadata: Record<string, unknown>; recipient_id: string; title: string; type: string } };
  Notifications: undefined;
  ManagerConversation: { participantId: string };
  ManagerCreateProperty: undefined;
  ManagerCreateTenancy: undefined;
  ManagerEditProperty: { propertyId: string };
  ManagerProperties: undefined;
  ManagerPropertyDetails: { propertyId: string };
  ManagerTenancies: undefined;
  ManagerTenancyDetails: { tenancyId: string };
  Main: undefined;
  Onboarding: undefined;
  PropertyDetails: { propertyId: string };
  Privacy: undefined;
  Register: undefined;
  SendInvite: undefined;
  RoleUnavailable: undefined;
  TenantConversation: { participantId: string };
  TenantPayments: undefined;
  Terms: undefined;
};
