/**
 * Every country, with its dialling code and its currency.
 *
 * Generated from ISO 3166 and the international dialling plan, so a manager
 * anywhere can register a phone number and list a property. East Africa is
 * listed first because that is where Axis operates; the rest follow A to Z.
 */

export type Country = { code: string; name: string; dial: string; flag: string; currency: string };

export const COUNTRIES: Country[] = [
  { code: 'UG', name: 'Uganda', dial: '256', flag: '🇺🇬', currency: 'UGX' },
  { code: 'KE', name: 'Kenya', dial: '254', flag: '🇰🇪', currency: 'KES' },
  { code: 'TZ', name: 'Tanzania', dial: '255', flag: '🇹🇿', currency: 'TZS' },
  { code: 'RW', name: 'Rwanda', dial: '250', flag: '🇷🇼', currency: 'RWF' },
  { code: 'BI', name: 'Burundi', dial: '257', flag: '🇧🇮', currency: 'BIF' },
  { code: 'SS', name: 'South Sudan', dial: '211', flag: '🇸🇸', currency: 'SSP' },
  { code: 'CD', name: 'Congo, The Democratic Republic of the', dial: '243', flag: '🇨🇩', currency: 'CDF' },
  { code: 'ET', name: 'Ethiopia', dial: '251', flag: '🇪🇹', currency: 'ETB' },
  { code: 'SO', name: 'Somalia', dial: '252', flag: '🇸🇴', currency: 'SOS' },
  { code: 'AF', name: 'Afghanistan', dial: '93', flag: '🇦🇫', currency: 'AFN' },
  { code: 'AL', name: 'Albania', dial: '355', flag: '🇦🇱', currency: 'ALL' },
  { code: 'DZ', name: 'Algeria', dial: '213', flag: '🇩🇿', currency: 'DZD' },
  { code: 'AS', name: 'American Samoa', dial: '1', flag: '🇦🇸', currency: 'USD' },
  { code: 'AD', name: 'Andorra', dial: '376', flag: '🇦🇩', currency: 'EUR' },
  { code: 'AO', name: 'Angola', dial: '244', flag: '🇦🇴', currency: 'AOA' },
  { code: 'AI', name: 'Anguilla', dial: '1', flag: '🇦🇮', currency: 'XCD' },
  { code: 'AG', name: 'Antigua and Barbuda', dial: '1', flag: '🇦🇬', currency: 'XCD' },
  { code: 'AR', name: 'Argentina', dial: '54', flag: '🇦🇷', currency: 'ARS' },
  { code: 'AM', name: 'Armenia', dial: '374', flag: '🇦🇲', currency: 'AMD' },
  { code: 'AW', name: 'Aruba', dial: '297', flag: '🇦🇼', currency: 'AWG' },
  { code: 'AU', name: 'Australia', dial: '61', flag: '🇦🇺', currency: 'AUD' },
  { code: 'AT', name: 'Austria', dial: '43', flag: '🇦🇹', currency: 'EUR' },
  { code: 'AZ', name: 'Azerbaijan', dial: '994', flag: '🇦🇿', currency: 'AZN' },
  { code: 'BS', name: 'Bahamas', dial: '1', flag: '🇧🇸', currency: 'BSD' },
  { code: 'BH', name: 'Bahrain', dial: '973', flag: '🇧🇭', currency: 'BHD' },
  { code: 'BD', name: 'Bangladesh', dial: '880', flag: '🇧🇩', currency: 'BDT' },
  { code: 'BB', name: 'Barbados', dial: '1', flag: '🇧🇧', currency: 'BBD' },
  { code: 'BY', name: 'Belarus', dial: '375', flag: '🇧🇾', currency: 'BYN' },
  { code: 'BE', name: 'Belgium', dial: '32', flag: '🇧🇪', currency: 'EUR' },
  { code: 'BZ', name: 'Belize', dial: '501', flag: '🇧🇿', currency: 'BZD' },
  { code: 'BJ', name: 'Benin', dial: '229', flag: '🇧🇯', currency: 'XOF' },
  { code: 'BM', name: 'Bermuda', dial: '1', flag: '🇧🇲', currency: 'BMD' },
  { code: 'BT', name: 'Bhutan', dial: '975', flag: '🇧🇹', currency: 'BTN' },
  { code: 'BO', name: 'Bolivia', dial: '591', flag: '🇧🇴', currency: 'BOB' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', dial: '599', flag: '🇧🇶', currency: 'USD' },
  { code: 'BA', name: 'Bosnia and Herzegovina', dial: '387', flag: '🇧🇦', currency: 'BAM' },
  { code: 'BW', name: 'Botswana', dial: '267', flag: '🇧🇼', currency: 'BWP' },
  { code: 'BR', name: 'Brazil', dial: '55', flag: '🇧🇷', currency: 'BRL' },
  { code: 'IO', name: 'British Indian Ocean Territory', dial: '246', flag: '🇮🇴', currency: 'USD' },
  { code: 'BN', name: 'Brunei Darussalam', dial: '673', flag: '🇧🇳', currency: 'BND' },
  { code: 'BG', name: 'Bulgaria', dial: '359', flag: '🇧🇬', currency: 'BGN' },
  { code: 'BF', name: 'Burkina Faso', dial: '226', flag: '🇧🇫', currency: 'XOF' },
  { code: 'CV', name: 'Cabo Verde', dial: '238', flag: '🇨🇻', currency: 'CVE' },
  { code: 'KH', name: 'Cambodia', dial: '855', flag: '🇰🇭', currency: 'KHR' },
  { code: 'CM', name: 'Cameroon', dial: '237', flag: '🇨🇲', currency: 'XAF' },
  { code: 'CA', name: 'Canada', dial: '1', flag: '🇨🇦', currency: 'CAD' },
  { code: 'KY', name: 'Cayman Islands', dial: '1', flag: '🇰🇾', currency: 'KYD' },
  { code: 'CF', name: 'Central African Republic', dial: '236', flag: '🇨🇫', currency: 'XAF' },
  { code: 'TD', name: 'Chad', dial: '235', flag: '🇹🇩', currency: 'XAF' },
  { code: 'CL', name: 'Chile', dial: '56', flag: '🇨🇱', currency: 'CLP' },
  { code: 'CN', name: 'China', dial: '86', flag: '🇨🇳', currency: 'CNY' },
  { code: 'CX', name: 'Christmas Island', dial: '61', flag: '🇨🇽', currency: 'AUD' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', dial: '61', flag: '🇨🇨', currency: 'AUD' },
  { code: 'CO', name: 'Colombia', dial: '57', flag: '🇨🇴', currency: 'COP' },
  { code: 'KM', name: 'Comoros', dial: '269', flag: '🇰🇲', currency: 'KMF' },
  { code: 'CG', name: 'Congo', dial: '242', flag: '🇨🇬', currency: 'XAF' },
  { code: 'CK', name: 'Cook Islands', dial: '682', flag: '🇨🇰', currency: 'NZD' },
  { code: 'CR', name: 'Costa Rica', dial: '506', flag: '🇨🇷', currency: 'CRC' },
  { code: 'HR', name: 'Croatia', dial: '385', flag: '🇭🇷', currency: 'EUR' },
  { code: 'CU', name: 'Cuba', dial: '53', flag: '🇨🇺', currency: 'CUP' },
  { code: 'CW', name: 'Curaçao', dial: '599', flag: '🇨🇼', currency: 'ANG' },
  { code: 'CY', name: 'Cyprus', dial: '357', flag: '🇨🇾', currency: 'EUR' },
  { code: 'CZ', name: 'Czechia', dial: '420', flag: '🇨🇿', currency: 'CZK' },
  { code: 'CI', name: 'Côte d\'Ivoire', dial: '225', flag: '🇨🇮', currency: 'XOF' },
  { code: 'DK', name: 'Denmark', dial: '45', flag: '🇩🇰', currency: 'DKK' },
  { code: 'DJ', name: 'Djibouti', dial: '253', flag: '🇩🇯', currency: 'DJF' },
  { code: 'DM', name: 'Dominica', dial: '1', flag: '🇩🇲', currency: 'XCD' },
  { code: 'DO', name: 'Dominican Republic', dial: '1', flag: '🇩🇴', currency: 'DOP' },
  { code: 'EC', name: 'Ecuador', dial: '593', flag: '🇪🇨', currency: 'USD' },
  { code: 'EG', name: 'Egypt', dial: '20', flag: '🇪🇬', currency: 'EGP' },
  { code: 'SV', name: 'El Salvador', dial: '503', flag: '🇸🇻', currency: 'USD' },
  { code: 'GQ', name: 'Equatorial Guinea', dial: '240', flag: '🇬🇶', currency: 'XAF' },
  { code: 'ER', name: 'Eritrea', dial: '291', flag: '🇪🇷', currency: 'ERN' },
  { code: 'EE', name: 'Estonia', dial: '372', flag: '🇪🇪', currency: 'EUR' },
  { code: 'SZ', name: 'Eswatini', dial: '268', flag: '🇸🇿', currency: 'SZL' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', dial: '500', flag: '🇫🇰', currency: 'FKP' },
  { code: 'FO', name: 'Faroe Islands', dial: '298', flag: '🇫🇴', currency: 'DKK' },
  { code: 'FJ', name: 'Fiji', dial: '679', flag: '🇫🇯', currency: 'FJD' },
  { code: 'FI', name: 'Finland', dial: '358', flag: '🇫🇮', currency: 'EUR' },
  { code: 'FR', name: 'France', dial: '33', flag: '🇫🇷', currency: 'EUR' },
  { code: 'GF', name: 'French Guiana', dial: '594', flag: '🇬🇫', currency: 'EUR' },
  { code: 'PF', name: 'French Polynesia', dial: '689', flag: '🇵🇫', currency: 'XPF' },
  { code: 'GA', name: 'Gabon', dial: '241', flag: '🇬🇦', currency: 'XAF' },
  { code: 'GM', name: 'Gambia', dial: '220', flag: '🇬🇲', currency: 'GMD' },
  { code: 'GE', name: 'Georgia', dial: '995', flag: '🇬🇪', currency: 'GEL' },
  { code: 'DE', name: 'Germany', dial: '49', flag: '🇩🇪', currency: 'EUR' },
  { code: 'GH', name: 'Ghana', dial: '233', flag: '🇬🇭', currency: 'GHS' },
  { code: 'GI', name: 'Gibraltar', dial: '350', flag: '🇬🇮', currency: 'GIP' },
  { code: 'GR', name: 'Greece', dial: '30', flag: '🇬🇷', currency: 'EUR' },
  { code: 'GL', name: 'Greenland', dial: '299', flag: '🇬🇱', currency: 'DKK' },
  { code: 'GD', name: 'Grenada', dial: '1', flag: '🇬🇩', currency: 'XCD' },
  { code: 'GP', name: 'Guadeloupe', dial: '590', flag: '🇬🇵', currency: 'EUR' },
  { code: 'GU', name: 'Guam', dial: '1', flag: '🇬🇺', currency: 'USD' },
  { code: 'GT', name: 'Guatemala', dial: '502', flag: '🇬🇹', currency: 'GTQ' },
  { code: 'GG', name: 'Guernsey', dial: '44', flag: '🇬🇬', currency: 'GBP' },
  { code: 'GN', name: 'Guinea', dial: '224', flag: '🇬🇳', currency: 'GNF' },
  { code: 'GW', name: 'Guinea-Bissau', dial: '245', flag: '🇬🇼', currency: 'XOF' },
  { code: 'GY', name: 'Guyana', dial: '592', flag: '🇬🇾', currency: 'GYD' },
  { code: 'HT', name: 'Haiti', dial: '509', flag: '🇭🇹', currency: 'HTG' },
  { code: 'VA', name: 'Holy See (Vatican City State)', dial: '39', flag: '🇻🇦', currency: 'EUR' },
  { code: 'HN', name: 'Honduras', dial: '504', flag: '🇭🇳', currency: 'HNL' },
  { code: 'HK', name: 'Hong Kong', dial: '852', flag: '🇭🇰', currency: 'HKD' },
  { code: 'HU', name: 'Hungary', dial: '36', flag: '🇭🇺', currency: 'HUF' },
  { code: 'IS', name: 'Iceland', dial: '354', flag: '🇮🇸', currency: 'ISK' },
  { code: 'IN', name: 'India', dial: '91', flag: '🇮🇳', currency: 'INR' },
  { code: 'ID', name: 'Indonesia', dial: '62', flag: '🇮🇩', currency: 'IDR' },
  { code: 'IR', name: 'Iran', dial: '98', flag: '🇮🇷', currency: 'IRR' },
  { code: 'IQ', name: 'Iraq', dial: '964', flag: '🇮🇶', currency: 'IQD' },
  { code: 'IE', name: 'Ireland', dial: '353', flag: '🇮🇪', currency: 'EUR' },
  { code: 'IM', name: 'Isle of Man', dial: '44', flag: '🇮🇲', currency: 'GBP' },
  { code: 'IL', name: 'Israel', dial: '972', flag: '🇮🇱', currency: 'ILS' },
  { code: 'IT', name: 'Italy', dial: '39', flag: '🇮🇹', currency: 'EUR' },
  { code: 'JM', name: 'Jamaica', dial: '1', flag: '🇯🇲', currency: 'JMD' },
  { code: 'JP', name: 'Japan', dial: '81', flag: '🇯🇵', currency: 'JPY' },
  { code: 'JE', name: 'Jersey', dial: '44', flag: '🇯🇪', currency: 'GBP' },
  { code: 'JO', name: 'Jordan', dial: '962', flag: '🇯🇴', currency: 'JOD' },
  { code: 'KZ', name: 'Kazakhstan', dial: '7', flag: '🇰🇿', currency: 'KZT' },
  { code: 'KI', name: 'Kiribati', dial: '686', flag: '🇰🇮', currency: 'AUD' },
  { code: 'KW', name: 'Kuwait', dial: '965', flag: '🇰🇼', currency: 'KWD' },
  { code: 'KG', name: 'Kyrgyzstan', dial: '996', flag: '🇰🇬', currency: 'KGS' },
  { code: 'LA', name: 'Laos', dial: '856', flag: '🇱🇦', currency: 'LAK' },
  { code: 'LV', name: 'Latvia', dial: '371', flag: '🇱🇻', currency: 'EUR' },
  { code: 'LB', name: 'Lebanon', dial: '961', flag: '🇱🇧', currency: 'LBP' },
  { code: 'LS', name: 'Lesotho', dial: '266', flag: '🇱🇸', currency: 'LSL' },
  { code: 'LR', name: 'Liberia', dial: '231', flag: '🇱🇷', currency: 'LRD' },
  { code: 'LY', name: 'Libya', dial: '218', flag: '🇱🇾', currency: 'LYD' },
  { code: 'LI', name: 'Liechtenstein', dial: '423', flag: '🇱🇮', currency: 'CHF' },
  { code: 'LT', name: 'Lithuania', dial: '370', flag: '🇱🇹', currency: 'EUR' },
  { code: 'LU', name: 'Luxembourg', dial: '352', flag: '🇱🇺', currency: 'EUR' },
  { code: 'MO', name: 'Macao', dial: '853', flag: '🇲🇴', currency: 'MOP' },
  { code: 'MG', name: 'Madagascar', dial: '261', flag: '🇲🇬', currency: 'MGA' },
  { code: 'MW', name: 'Malawi', dial: '265', flag: '🇲🇼', currency: 'MWK' },
  { code: 'MY', name: 'Malaysia', dial: '60', flag: '🇲🇾', currency: 'MYR' },
  { code: 'MV', name: 'Maldives', dial: '960', flag: '🇲🇻', currency: 'MVR' },
  { code: 'ML', name: 'Mali', dial: '223', flag: '🇲🇱', currency: 'XOF' },
  { code: 'MT', name: 'Malta', dial: '356', flag: '🇲🇹', currency: 'EUR' },
  { code: 'MH', name: 'Marshall Islands', dial: '692', flag: '🇲🇭', currency: 'USD' },
  { code: 'MQ', name: 'Martinique', dial: '596', flag: '🇲🇶', currency: 'EUR' },
  { code: 'MR', name: 'Mauritania', dial: '222', flag: '🇲🇷', currency: 'MRU' },
  { code: 'MU', name: 'Mauritius', dial: '230', flag: '🇲🇺', currency: 'MUR' },
  { code: 'YT', name: 'Mayotte', dial: '262', flag: '🇾🇹', currency: 'EUR' },
  { code: 'MX', name: 'Mexico', dial: '52', flag: '🇲🇽', currency: 'MXN' },
  { code: 'FM', name: 'Micronesia, Federated States of', dial: '691', flag: '🇫🇲', currency: 'USD' },
  { code: 'MD', name: 'Moldova', dial: '373', flag: '🇲🇩', currency: 'MDL' },
  { code: 'MC', name: 'Monaco', dial: '377', flag: '🇲🇨', currency: 'EUR' },
  { code: 'MN', name: 'Mongolia', dial: '976', flag: '🇲🇳', currency: 'MNT' },
  { code: 'ME', name: 'Montenegro', dial: '382', flag: '🇲🇪', currency: 'EUR' },
  { code: 'MS', name: 'Montserrat', dial: '1', flag: '🇲🇸', currency: 'XCD' },
  { code: 'MA', name: 'Morocco', dial: '212', flag: '🇲🇦', currency: 'MAD' },
  { code: 'MZ', name: 'Mozambique', dial: '258', flag: '🇲🇿', currency: 'MZN' },
  { code: 'MM', name: 'Myanmar', dial: '95', flag: '🇲🇲', currency: 'MMK' },
  { code: 'NA', name: 'Namibia', dial: '264', flag: '🇳🇦', currency: 'NAD' },
  { code: 'NR', name: 'Nauru', dial: '674', flag: '🇳🇷', currency: 'AUD' },
  { code: 'NP', name: 'Nepal', dial: '977', flag: '🇳🇵', currency: 'NPR' },
  { code: 'NL', name: 'Netherlands', dial: '31', flag: '🇳🇱', currency: 'EUR' },
  { code: 'NC', name: 'New Caledonia', dial: '687', flag: '🇳🇨', currency: 'XPF' },
  { code: 'NZ', name: 'New Zealand', dial: '64', flag: '🇳🇿', currency: 'NZD' },
  { code: 'NI', name: 'Nicaragua', dial: '505', flag: '🇳🇮', currency: 'NIO' },
  { code: 'NE', name: 'Niger', dial: '227', flag: '🇳🇪', currency: 'XOF' },
  { code: 'NG', name: 'Nigeria', dial: '234', flag: '🇳🇬', currency: 'NGN' },
  { code: 'NU', name: 'Niue', dial: '683', flag: '🇳🇺', currency: 'NZD' },
  { code: 'NF', name: 'Norfolk Island', dial: '672', flag: '🇳🇫', currency: 'AUD' },
  { code: 'KP', name: 'North Korea', dial: '850', flag: '🇰🇵', currency: 'KPW' },
  { code: 'MK', name: 'North Macedonia', dial: '389', flag: '🇲🇰', currency: 'MKD' },
  { code: 'MP', name: 'Northern Mariana Islands', dial: '1', flag: '🇲🇵', currency: 'USD' },
  { code: 'NO', name: 'Norway', dial: '47', flag: '🇳🇴', currency: 'NOK' },
  { code: 'OM', name: 'Oman', dial: '968', flag: '🇴🇲', currency: 'OMR' },
  { code: 'PK', name: 'Pakistan', dial: '92', flag: '🇵🇰', currency: 'PKR' },
  { code: 'PW', name: 'Palau', dial: '680', flag: '🇵🇼', currency: 'USD' },
  { code: 'PS', name: 'Palestine, State of', dial: '970', flag: '🇵🇸', currency: 'ILS' },
  { code: 'PA', name: 'Panama', dial: '507', flag: '🇵🇦', currency: 'PAB' },
  { code: 'PG', name: 'Papua New Guinea', dial: '675', flag: '🇵🇬', currency: 'PGK' },
  { code: 'PY', name: 'Paraguay', dial: '595', flag: '🇵🇾', currency: 'PYG' },
  { code: 'PE', name: 'Peru', dial: '51', flag: '🇵🇪', currency: 'PEN' },
  { code: 'PH', name: 'Philippines', dial: '63', flag: '🇵🇭', currency: 'PHP' },
  { code: 'PL', name: 'Poland', dial: '48', flag: '🇵🇱', currency: 'PLN' },
  { code: 'PT', name: 'Portugal', dial: '351', flag: '🇵🇹', currency: 'EUR' },
  { code: 'PR', name: 'Puerto Rico', dial: '1', flag: '🇵🇷', currency: 'USD' },
  { code: 'QA', name: 'Qatar', dial: '974', flag: '🇶🇦', currency: 'QAR' },
  { code: 'RO', name: 'Romania', dial: '40', flag: '🇷🇴', currency: 'RON' },
  { code: 'RU', name: 'Russian Federation', dial: '7', flag: '🇷🇺', currency: 'RUB' },
  { code: 'RE', name: 'Réunion', dial: '262', flag: '🇷🇪', currency: 'EUR' },
  { code: 'BL', name: 'Saint Barthélemy', dial: '590', flag: '🇧🇱', currency: 'EUR' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', dial: '290', flag: '🇸🇭', currency: 'SHP' },
  { code: 'KN', name: 'Saint Kitts and Nevis', dial: '1', flag: '🇰🇳', currency: 'XCD' },
  { code: 'LC', name: 'Saint Lucia', dial: '1', flag: '🇱🇨', currency: 'XCD' },
  { code: 'MF', name: 'Saint Martin (French part)', dial: '590', flag: '🇲🇫', currency: 'EUR' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', dial: '508', flag: '🇵🇲', currency: 'EUR' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', dial: '1', flag: '🇻🇨', currency: 'XCD' },
  { code: 'WS', name: 'Samoa', dial: '685', flag: '🇼🇸', currency: 'WST' },
  { code: 'SM', name: 'San Marino', dial: '378', flag: '🇸🇲', currency: 'EUR' },
  { code: 'ST', name: 'Sao Tome and Principe', dial: '239', flag: '🇸🇹', currency: 'STN' },
  { code: 'SA', name: 'Saudi Arabia', dial: '966', flag: '🇸🇦', currency: 'SAR' },
  { code: 'SN', name: 'Senegal', dial: '221', flag: '🇸🇳', currency: 'XOF' },
  { code: 'RS', name: 'Serbia', dial: '381', flag: '🇷🇸', currency: 'RSD' },
  { code: 'SC', name: 'Seychelles', dial: '248', flag: '🇸🇨', currency: 'SCR' },
  { code: 'SL', name: 'Sierra Leone', dial: '232', flag: '🇸🇱', currency: 'SLE' },
  { code: 'SG', name: 'Singapore', dial: '65', flag: '🇸🇬', currency: 'SGD' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', dial: '1', flag: '🇸🇽', currency: 'ANG' },
  { code: 'SK', name: 'Slovakia', dial: '421', flag: '🇸🇰', currency: 'EUR' },
  { code: 'SI', name: 'Slovenia', dial: '386', flag: '🇸🇮', currency: 'EUR' },
  { code: 'SB', name: 'Solomon Islands', dial: '677', flag: '🇸🇧', currency: 'SBD' },
  { code: 'ZA', name: 'South Africa', dial: '27', flag: '🇿🇦', currency: 'ZAR' },
  { code: 'KR', name: 'South Korea', dial: '82', flag: '🇰🇷', currency: 'KRW' },
  { code: 'ES', name: 'Spain', dial: '34', flag: '🇪🇸', currency: 'EUR' },
  { code: 'LK', name: 'Sri Lanka', dial: '94', flag: '🇱🇰', currency: 'LKR' },
  { code: 'SD', name: 'Sudan', dial: '249', flag: '🇸🇩', currency: 'SDG' },
  { code: 'SR', name: 'Suriname', dial: '597', flag: '🇸🇷', currency: 'SRD' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', dial: '47', flag: '🇸🇯', currency: 'NOK' },
  { code: 'SE', name: 'Sweden', dial: '46', flag: '🇸🇪', currency: 'SEK' },
  { code: 'CH', name: 'Switzerland', dial: '41', flag: '🇨🇭', currency: 'CHF' },
  { code: 'SY', name: 'Syria', dial: '963', flag: '🇸🇾', currency: 'SYP' },
  { code: 'TW', name: 'Taiwan', dial: '886', flag: '🇹🇼', currency: 'TWD' },
  { code: 'TJ', name: 'Tajikistan', dial: '992', flag: '🇹🇯', currency: 'TJS' },
  { code: 'TH', name: 'Thailand', dial: '66', flag: '🇹🇭', currency: 'THB' },
  { code: 'TL', name: 'Timor-Leste', dial: '670', flag: '🇹🇱', currency: 'USD' },
  { code: 'TG', name: 'Togo', dial: '228', flag: '🇹🇬', currency: 'XOF' },
  { code: 'TK', name: 'Tokelau', dial: '690', flag: '🇹🇰', currency: 'NZD' },
  { code: 'TO', name: 'Tonga', dial: '676', flag: '🇹🇴', currency: 'TOP' },
  { code: 'TT', name: 'Trinidad and Tobago', dial: '1', flag: '🇹🇹', currency: 'TTD' },
  { code: 'TN', name: 'Tunisia', dial: '216', flag: '🇹🇳', currency: 'TND' },
  { code: 'TM', name: 'Turkmenistan', dial: '993', flag: '🇹🇲', currency: 'TMT' },
  { code: 'TC', name: 'Turks and Caicos Islands', dial: '1', flag: '🇹🇨', currency: 'USD' },
  { code: 'TV', name: 'Tuvalu', dial: '688', flag: '🇹🇻', currency: 'AUD' },
  { code: 'TR', name: 'Türkiye', dial: '90', flag: '🇹🇷', currency: 'TRY' },
  { code: 'UA', name: 'Ukraine', dial: '380', flag: '🇺🇦', currency: 'UAH' },
  { code: 'AE', name: 'United Arab Emirates', dial: '971', flag: '🇦🇪', currency: 'AED' },
  { code: 'GB', name: 'United Kingdom', dial: '44', flag: '🇬🇧', currency: 'GBP' },
  { code: 'US', name: 'United States', dial: '1', flag: '🇺🇸', currency: 'USD' },
  { code: 'UY', name: 'Uruguay', dial: '598', flag: '🇺🇾', currency: 'UYU' },
  { code: 'UZ', name: 'Uzbekistan', dial: '998', flag: '🇺🇿', currency: 'UZS' },
  { code: 'VU', name: 'Vanuatu', dial: '678', flag: '🇻🇺', currency: 'VUV' },
  { code: 'VE', name: 'Venezuela', dial: '58', flag: '🇻🇪', currency: 'VES' },
  { code: 'VN', name: 'Vietnam', dial: '84', flag: '🇻🇳', currency: 'VND' },
  { code: 'VG', name: 'Virgin Islands, British', dial: '1', flag: '🇻🇬', currency: 'USD' },
  { code: 'VI', name: 'Virgin Islands, U.S.', dial: '1', flag: '🇻🇮', currency: 'USD' },
  { code: 'WF', name: 'Wallis and Futuna', dial: '681', flag: '🇼🇫', currency: 'XPF' },
  { code: 'EH', name: 'Western Sahara', dial: '212', flag: '🇪🇭', currency: 'MAD' },
  { code: 'YE', name: 'Yemen', dial: '967', flag: '🇾🇪', currency: 'YER' },
  { code: 'ZM', name: 'Zambia', dial: '260', flag: '🇿🇲', currency: 'ZMW' },
  { code: 'ZW', name: 'Zimbabwe', dial: '263', flag: '🇿🇼', currency: 'ZWL' },
  { code: 'AX', name: 'Åland Islands', dial: '358', flag: '🇦🇽', currency: 'EUR' },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // Uganda

/**
 * Longest dial codes first, so +255 is never read as +25. Where two
 * countries share a code (+1 is both the US and Canada), the first listed
 * here wins, so a +1 number shows as the United States.
 */
const SHARED_CODE_PREFERENCE = ['US'];
const BY_LENGTH = [...COUNTRIES].sort(
  (a, b) =>
    b.dial.length - a.dial.length ||
    Number(SHARED_CODE_PREFERENCE.includes(b.code)) - Number(SHARED_CODE_PREFERENCE.includes(a.code)),
);

/** Split a stored number into the country and the local part. */
export function splitPhone(value: string | null | undefined): { country: Country; national: string } {
  const digits = String(value || '').replace(/[^\d+]/g, '').replace(/^\+/, '');
  if (!digits) return { country: DEFAULT_COUNTRY, national: '' };
  for (const country of BY_LENGTH) {
    if (digits.startsWith(country.dial) && digits.length > country.dial.length) {
      return { country, national: digits.slice(country.dial.length) };
    }
  }
  return { country: DEFAULT_COUNTRY, national: digits.replace(/^0+/, '') };
}

/** Join a country and a typed local number into "+256752738927". */
export function joinPhone(country: Country, national: string): string {
  const local = String(national || '').replace(/\D/g, '').replace(/^0+/, '');
  return local ? `+${country.dial}${local}` : '';
}
