import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import {
  documentDirectory,
  writeAsStringAsync,
  makeDirectoryAsync,
  StorageAccessFramework,
} from "expo-file-system/legacy";
import { Alert, Platform } from "react-native";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildCsvRows(
  headers: string[],
  rows: (string | number | null | undefined)[][]
): string {
  const sanitize = (val: unknown): string => {
    const s = String(val ?? "");
    return `"${s.replace(/"/g, '""')}"`;
  };
  return [headers.map(sanitize).join(","), ...rows.map((r) => r.map(sanitize).join(","))].join("\n");
}

export function buildHtmlTable(
  title: string,
  subtitle: string,
  headers: string[],
  rows: (string | number | null | undefined)[][]
): string {
  const thead = headers
    .map(
      (h) =>
        `<th style="padding:8px 12px;text-align:left;border-bottom:2px solid #2E7D52;color:#2E7D52;font-weight:700;font-size:13px;white-space:nowrap;">${escapeHtml(h)}</th>`
    )
    .join("");
  const tbody = rows
    .map(
      (r) =>
        `<tr>${r
          .map(
            (c) =>
              `<td style="padding:8px 12px;border-bottom:1px solid #e0e0e0;font-size:12px;">${escapeHtml(String(c ?? ""))}</td>`
          )
          .join("")}</tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8" /></head>
<body style="font-family:-apple-system,Helvetica,Arial,sans-serif;padding:24px;color:#222;">
  <h1 style="font-size:22px;margin:0 0 4px;color:#1a1a1a;">${escapeHtml(title)}</h1>
  <p style="font-size:13px;color:#666;margin:0 0 24px;">${escapeHtml(subtitle)}</p>
  <table style="width:100%;border-collapse:collapse;">
    <thead>${thead}</thead>
    <tbody>${tbody}</tbody>
  </table>
  <p style="font-size:10px;color:#999;margin-top:24px;text-align:center;">
    Generated by Axis Housing — ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })}
  </p>
</body>
</html>`;
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "-").replace(/-+/g, "-");
}

function fileName(prefix: string, ext: string): string {
  const date = new Date().toISOString().slice(0, 10);
  return sanitizeFilename(`${prefix}-${date}.${ext}`);
}

const REPORTS_DIR = `${documentDirectory}reports/`;

async function ensureReportsDir(): Promise<void> {
  try {
    await makeDirectoryAsync(REPORTS_DIR, { intermediates: true });
  } catch {
    // directory already exists
  }
}

/**
 * Write content (base64 for PDF, plain text for CSV) to both:
 * 1. App's persistent reports directory (always works)
 * 2. Public Downloads folder via SAF (Android, may fail on API 30+)
 */
async function writeToStorage(
  content: string,
  filename: string,
  mimeType: string,
  isBase64: boolean
): Promise<{ savedTo: "downloads" | "app_storage"; path: string }> {
  const encoding = isBase64 ? "base64" : "utf8";
  const ext = isBase64 ? "pdf" : "csv";

  // 1. Always save to app's persistent storage
  try {
    await ensureReportsDir();
    await writeAsStringAsync(`${REPORTS_DIR}${filename}`, content, { encoding });
  } catch {
    return { savedTo: "app_storage", path: `${REPORTS_DIR}${filename}` };
  }

  // 2. Try to also save to public Downloads via SAF (Android only)
  if (Platform.OS === "android") {
    try {
      const downloadsUri = StorageAccessFramework.getUriForDirectoryInRoot("Downloads");
      const safeUri = await StorageAccessFramework.createFileAsync(
        downloadsUri,
        filename.replace(/\.[^.]+$/, ""),
        mimeType
      );
      await StorageAccessFramework.writeAsStringAsync(safeUri, content, { encoding });
      return { savedTo: "downloads", path: `Downloads/${filename}` };
    } catch {
      // SAF not available on this device — file is already saved in app storage
    }
  }

  return { savedTo: "app_storage", path: `${REPORTS_DIR}${filename}` };
}

/**
 * Generate PDF and save directly to device storage.
 * Uses expo-print with base64:true so no file read is needed.
 */
export async function downloadPdf(
  title: string,
  subtitle: string,
  headers: string[],
  rows: (string | number | null | undefined)[][],
  prefix: string
): Promise<{ savedTo: "downloads" | "app_storage" | "failed"; path: string }> {
  try {
    const html = buildHtmlTable(title, subtitle, headers, rows);
    const { base64 } = await Print.printToFileAsync({ html, base64: true });
    if (!base64) return { savedTo: "failed", path: "" };
    const filename = fileName(prefix, "pdf");
    return await writeToStorage(base64, filename, "application/pdf", true);
  } catch {
    return { savedTo: "failed", path: "" };
  }
}

/**
 * Generate CSV and save directly to device storage.
 */
export async function downloadCsv(
  headers: string[],
  rows: (string | number | null | undefined)[][],
  prefix: string
): Promise<{ savedTo: "downloads" | "app_storage" | "failed"; path: string }> {
  try {
    const csv = buildCsvRows(headers, rows);
    const filename = fileName(prefix, "csv");
    return await writeToStorage(csv, filename, "text/csv", false);
  } catch {
    return { savedTo: "failed", path: "" };
  }
}

/**
 * Share a report via the system share sheet (WhatsApp, email, etc.)
 */
export async function shareReport(
  title: string,
  subtitle: string,
  headers: string[],
  rows: (string | number | null | undefined)[][],
  prefix: string,
  format: "pdf" | "csv"
): Promise<boolean> {
  try {
    const filename = fileName(prefix, format);
    let uri: string;
    if (format === "pdf") {
      const html = buildHtmlTable(title, subtitle, headers, rows);
      const result = await Print.printToFileAsync({ html, base64: false });
      uri = result.uri;
    } else {
      const csv = buildCsvRows(headers, rows);
      await ensureReportsDir();
      uri = `${REPORTS_DIR}${filename}`;
      await writeAsStringAsync(uri, csv, { encoding: "utf8" });
    }
    const isAvailable = await Sharing.isAvailableAsync();
    if (!isAvailable) return false;
    const mimeType = format === "pdf" ? "application/pdf" : "text/csv";
    await Sharing.shareAsync(uri, { mimeType, dialogTitle: `Share ${filename}` });
    return true;
  } catch {
    return false;
  }
}
